language: python
python:
  - "2.7"
  - "2.6"
env:
  global:
    - SOUTH_TESTS_MIGRATE=1
  matrix:
    - DATABASE_ENGINE=sqlite DJANGO_PACKAGE='Django>=1.4,<1.5'
    - DATABASE_ENGINE=sqlite DJANGO_PACKAGE='Django>=1.5,<1.6'
    - DATABASE_ENGINE=sqlite DJANGO_PACKAGE='Django>=1.6,<1.7'
    - DATABASE_ENGINE=postgres DJANGO_PACKAGE='Django>=1.4,<1.5'
    - DATABASE_ENGINE=postgres DJANGO_PACKAGE='Django>=1.5,<1.6'
    - DATABASE_ENGINE=postgres DJANGO_PACKAGE='Django>=1.6,<1.7'
    - DATABASE_ENGINE=mysql DJANGO_PACKAGE='Django>=1.4,<1.5'
    - DATABASE_ENGINE=mysql DJANGO_PACKAGE='Django>=1.5,<1.6'
    - DATABASE_ENGINE=mysql DJANGO_PACKAGE='Django>=1.6,<1.7'
install:
  - pip install --upgrade pip
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - pip install -q --use-mirrors mock
  - |
    if [ "$DATABASE_ENGINE" = "mysql" ]
    then
      pip install -q --use-mirrors MySQL-python
    fi
  - |
    if [ "$DATABASE_ENGINE" = "postgres" ]
    then
      pip install -q --use-mirrors psycopg2
    fi
  - pip install --use-mirrors .
  - pip freeze
before_script:
  - psql -c 'create database widgy;' -U postgres
  - mysql -e 'create database widgy;'
script: make test-py
