language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
install:
  - pip instal -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: make test
